/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-29 16:24:46
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
//#define int long long
//const int INF = 0x7fffffffffffffff;
const int MAXN = 2003;
int a[MAXN * 15][MAXN], cnt[MAXN], n, q;

bool trans(int row) {
    bool ok = true;
    memset(cnt, 0, sizeof(cnt));
    for (int i = 1; i <= n; i++) cnt[a[row-1][i]]++;
    for (int i = 1; i <= n; i++) {
        a[row][i] = cnt[a[row-1][i]];
        if (a[row][i] != a[row-1][i]) ok = false;
    }
    return ok;
}

void solve () {
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> a[0][i];
    int maxK = 0;
    for (maxK = 1; ; maxK++) if(trans(maxK)) break;
    cin >> q;
    while (q--) {
        int x, k;
        cin >> x >> k;
        k = min(maxK, k);
        cout << a[k][x] << endl;
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}