/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-28 23:36:28
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    string s;
    cin >> s;
    int l = s.length();
    int index = 0;
    for (int i = 1; i < l; i++) {
        if (s[i] < s[index]) {
            index = i;
        }
    }
    string a = "", b = "";
    for (int i = 0; i < l; i++) {
        if (i == index) a += s[i];
        else b += s[i];
    }
    cout << a << ' ' << b << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}