/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-04 16:46:12
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int N, m, M, a;
    cin >> N;
    for (int i = 1; i <= N; i++) {
        cin >> a;
        if (a == 1) m = i;
        if (a == N) M = i;
    }

    int Ans = N + 1 - abs(m - M);
    Ans = min(Ans, max(m, M));
    Ans = min(Ans, N + 1 - min(m, M));
    cout << Ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}