/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-02 18:33:42
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int mod = 1e9+7;
const int MAXN = 2e5 + 9;

void solve () {
    int n, ans = 1;
    cin >> n;
    for (int i = 3; i <= 2 * n; i++) ans = (ans * i) % mod;
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}