/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-30 22:35:10
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int arr[MAXN], n;

bool is_increase() {
    for (int i = 1; i < n ; i++) {
        if (arr[i] >= arr[i+1]) return false;
    }
    return true;
}

void solve () {
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> arr[i];
    if (n % 2 == 0) cout << "YES" << endl;
    else cout << (is_increase() ? "NO" : "YES") << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}