/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-10 17:05:01
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int n;
    string a, b;
    cin >> n >> a >> b;
    bool ok = a[0] == '0';
    for (int i = 0; i < n; i++) {
        if (a[i] == '1' && b[i] == '1') {ok = false; break;}
    }
    if (ok) cout << "YES" << endl;
    else cout << "NO" << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}