/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-18 13:46:30
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int arr[MAXN], N;
void solve () {
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> arr[i];
    sort(arr+1, arr+1+N);
    arr[0] = 0;
    int mx = -INF;
    for (int i = 1; i <= N; i++) mx = max(mx, arr[i] - arr[i-1]);
    cout << mx << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}