/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-08 22:35:01
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e3 + 9;
int arr[MAXN], tmp[MAXN], ans[MAXN];

void solve () {
    int N;
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> arr[i];
    for (int j = N; j >= 1; j--) {
        if (arr[j] == j) { ans[j] = 0; continue; }
        int i;
        for (i = j; i >= 1; i--) {
            if (arr[i] == j) {
                break;
            }
        }
        ans[j] = i;
        for (int i0 = 1; i0 <= i; i0++) tmp[i0] = arr[i0];
        for (int i0 = i + 1; i0 <= j; i0++) arr[i0 - i] = arr[i0];
        for (int i0 = 1; i0 <= i; i0++) arr[i0 + j-i] = tmp[i0];
    }
    for (int i = 1; i < N; i++) cout << ans[i] << ' ';
    cout << ans[N] << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}