/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-24 15:41:41
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N, K, M;

int A(int n) { return n == 1 ? 1 : n * A(n-1); }
signed main() {
    fast_stream();
    set<int> s;s.clear();
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            for (int k = 0; k < 4; k++) {
                s.insert(100*i+10*j+k);
            }
        }
    }
    for (int i = 0; i < 4; i++) {
        for (int j = 0; j < 4; j++) {
            for (int k = 0; k < 4; k++) {
                if (i == k && (i | j) == (j | k)) {
                    s.erase(100*i+10*j+k);
                    s.erase(100*i+10*k+j);
                    s.erase(100*j+10*i+k);
                    s.erase(100*j+10*k+i);
                    s.erase(100*k+10*i+j);
                    s.erase(100*k+10*j+i);
                }
            }
        }
    }

    for (int s0 : s) {
        int i = s0 / 100, j = (s0 - 100*i) / 10, k = s0-100*i-10*j;
        printf("%d %d%d\n%d %d%d\n%d %d%d\n\n", i, i >> 1, i & 1, j, j >> 1, j & 1, k, k >> 1, k & 1);
    }
}

/**
 *
 *
 */



//1,5,0,2,4,4,1
// 001
// 101
// 000
// 010
// 100
// 100
// 001