/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-30 23:39:22
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
//#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e4 + 9;
int a[MAXN], sum[MAXN];

void solve () {
    int N, K;
    scanf("%d %d", &N, &K);
    for (int i = 1; i < N; i++) {
        int And, Or;
        printf("and %d %d\n", i, i + 1);
        fflush(stdout);
        scanf("%d", &And);
        printf("or %d %d\n", i, i + 1);
        fflush(stdout);
        scanf("%d", &Or);
        sum[i] = And + Or;
    }
    int And, Or;
    printf("and %d %d\n", 1, 3);
    fflush(stdout);
    scanf("%d", &And);
    printf("or %d %d\n", 1, 3);
    fflush(stdout);
    scanf("%d", &Or);
    int a13 = And + Or;
    a[2] = (sum[1] + sum[2] - a13) / 2;
    a[1] = sum[1] - a[2];
    a[3] = sum[2] - a[2];
    for (int i = 4; i <= N; i++) {
        a[i] = sum[i-1] - a[i-1];
    }
    sort(a+1, a+1+N);
    printf("finish %d\n", a[K]);
    fflush(stdout);
}

signed main() {
    fast_stream();
    int t;
//    cin >> t;
    t = 1;
    while (t--) {
        solve();
    }
}