/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-03 22:13:10
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
const int MOD = 1e9 + 1;
int N, T[MAXN], lastans = 0;

signed main() {
    fast_stream();
    cin >> N;
    for (int i = 1; i <= N; i++) {
        cin >> T[i];
        int K, X;
        cin >> K;
        while (K--) {
            cin >> X;
            X = (X + lastans) % MOD;
            for (int j = 1; j <= i; j++) {
                if (X < T[j]) X++;
                else if (X > T[j]) X--;
            }
            cout << X << endl;
            lastans = X;
        }
    }
}