/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-09 10:27:19
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 3e5 + 9;
int arr[MAXN], n;
bool check(int p) {
    for (int k = 1; k * p <= n; k++) if (!arr[k * p]) return false;
    return true;
}
void solve () {
    char ch; string s;
    cin >> n >> ch >> s;
    for (int i = 1; i <= n; i++) arr[i] = s[i-1] == ch;
    if (check(1)) cout << 0 << endl;
    else {
        for (int k = 2; k <= n; k++) {
            if (check(k)) {
                cout << "1\n" << k << endl;
                return;
            }
        }
        cout << "2\n" << n - 1 << ' ' << n << endl;
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}