/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-09 10:27:19
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    // < n / s false
    // > n false
    // == n true
    // (s-1, n-s+1) false

    // 4 2 3
    // [1,3] [2,2] [3,1]
    // 4 3 3
    // [1,1,2][1,2,1][2,1,1]
    // 56220 47258 14497
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}