/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-13 22:35:01
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int sv(string s, int z) {
    int l = s.length(), i;
    for (i = l - 1; i >= 0; i--) {
        if (s[i] == z + '0') break;
    }
    int ans = l - 1 - i, aq = 1e9;
    for (int j = i - 1; j >= 0; j--) {
        if (z == 0 && (s[j] == '0' || s[j] == '5')) {
            aq = i - j - 1;
            break;
        }
        if (z == 5 && (s[j] == '2' || s[j] == '7')) {
            aq = i - j - 1;
            break;
        }
    }
    return ans + aq;
}

void solve () {
    string s;
    cin >> s;
    cout << min(sv(s, 0), sv(s, 5)) << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}