/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-29 22:35:04
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
#define max(a, b) ((a < b) ? b : a);
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int upper(int a, int b) {
    int ans = a / b;
    if (a % b != 0) ans++;
    return ans;
}

void solve () {
    int n, k, hour = 0, has = 1;
    cin >> n >> k;
    while (1) {
        if (has >= n) { cout << hour << endl; return; }
        if (k >= has) { hour ++; has *= 2; }
        else break;
    }
    hour += upper(n - has, k);
    cout << hour << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}