/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-12 22:37:06
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int n, Ans = 0, bf = 0;
    string s1, s2;
    cin >> n >> s1 >> s2;
    for (int i = 0; i < n; i++) {
        if ((s1[i] == '0' && s2[i] == '1') || (s1[i] == '1' && s2[i] == '0')) {
            Ans += 2;
            bf = 0;
        } else if (s1[i] == '1' && s2[i] == '1') {
            bf = 1;
        } else {
            if (bf == 1) {
                Ans += 2;
                bf = 0;
            } else {
                if (i + 1 < n && (s1[i+1] == '1' && s2[i+1] == '1')) {
                    Ans += 2;
                    bf = 0;
                    i++;
                } else {
                    Ans += 1;
                    bf = 0;
                }
            }
        }
    }
    cout << Ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}