/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-30 23:39:22
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
int arr[MAXN], cnt[2];
set<int> s[2];

void init(int N) {
    s[0].clear(), s[1].clear();
    cnt[0] = cnt[1] = 0;
    for (int i = 1; i <= N; i++) s[arr[i]].insert(i), cnt[arr[i]]++;
}

void solve () {
    int N, total1 = 0, total2 = 0, last;
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> arr[i], arr[i] &= 1;

    init(N);
    if (abs(cnt[0] - cnt[1]) > 1) {
        cout << -1 << endl;
        return;
    }
    last = 0;
    for (int i = 1; i <= N; i++) {
        last = 1 - last;
        int j = *(s[last].begin());
        if (j == i) {
            s[last].erase(s[last].begin());
        } else {
            total1 += abs(i - j);
            s[1-last].erase(i);
            s[1-last].insert(j);
            s[last].erase(j);
        }
    }

    init(N);
    last = 1;
    for (int i = 1; i <= N; i++) {
        last = 1 - last;
        int j = *(s[last].begin());
        if (j == i) {
            s[last].erase(s[last].begin());
        } else {
            total2 += abs(i - j);
            s[1-last].erase(i);
            s[1-last].insert(j);
            s[last].erase(j);
        }
    }
    cout << min(total1, total2) << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}