/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-04 23:35:06
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int arr[MAXN];
void solve () {
    int N;
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> arr[i];
    sort(arr+1, arr+1+N);
    int lg = 0, ls = arr[1];
    for (int i = 1; 2 * i + 1 <= N; i++) {
        lg += arr[N + 1 - i];
        ls += arr[i + 1];
        if (lg > ls) {
            cout << "YES" << endl;
            return;
        }
    }
    cout << "NO" << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}