/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-30 23:39:22
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int a, b;
    cin >> a >> b;
    if (a == b && a == 0) {cout << 0 << endl; return;}
    int c = abs(a - b);
    if (c == 0) cout << 1 << endl;
    else if (c & 1) cout << -1 << endl;
    else cout << 2 << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}