/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-24 18:05:04
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
vector<vector<int>> dp[512];
int a[MAXN], n;


void solve () {
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> a[i];
    vector<int> v;
    v.push_back(a[n]);
    dp[a[n]].push_back(v);
    for (int i = n-1; i >= 1; i--) {
        for (int q = a[i] + 1; q <= 511; q++) {
            for (vector<int> has : dp[q]) {
                if (has.size() > 0 && has[has.size()-1] > a[i]){

                }
            }
        }
    }
}

signed main() {
    fast_stream();
    int t;
//    cin >> t;
    t = 1;
    while (t--) {
        solve();
    }
}