/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-02 18:33:42
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int d(int n, int m) {
    if (n == 1 && m == 0) return 0;
    if (m < n - 1) return INF;
    else if (m < (n - 1) * n / 2) return 2;
    else if (m == n * (n-1) / 2) return 1;
    else return INF;
}

void solve () {
    int n, m, k;
    cin >> n >> m >> k;
    cout << (d(n, m) < k - 1 ? "YES" : "NO") << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}