/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-12 22:37:06
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int n, s;
    cin >> n >> s;
    int q = (n + (n % 2 == 0 ? 2 : 1)) / 2;
    cout << (s / q) << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}