/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-30 18:38:49
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N, M, arr[MAXN], Ans = 0;

void dfs(int idx, int sum) {
    if (idx > N) {
        Ans += sum;
        return;
    }
    dfs(idx + 1, sum);
    dfs(idx + 1, sum ^ arr[idx]);
}

void solve () {
    cin >> N >> M;
    for (int i = 1; i <= N; i++) arr[i] = INF;
    while (M--) {
        int l, r, x;
        cin >> l >> r >> x;
        for (int i = l; i <= r; i++) arr[i] &= x;
    }
    Ans = 0;
    dfs(1, 0);
    cout << Ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}