/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-22 17:04:07
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    string s;
    cin >> s;
    int L = s.length();
    if (L % 2 == 1) {
        cout << "NO" << endl;
    } else {
        for (int i = 0; i < L / 2; i++) {
            if (s[i] != s[i + L / 2]) {
                cout << "NO" << endl;
                return;
            }
        }
        cout << "YES" << endl;
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}