/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-08 23:05:02
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
const int MOD = 1e9 + 7;
int N, K;

int Q(int n) {
    int ans = 0;
    while (n > 0) ans++, n >>= 1;
    return ans;
}
int ex_pow(int a, int b) {
    int base = a, ans = 1;
    while (b > 0) {
        if (b & 1) ans = (ans * base) % MOD;
        base = (base * base) % MOD;
        b >>= 1;
    }
    return ans;
}


void solve () {
    cin >> N >> K;
    int ans = 0;
    while (K > 0) {
        int q = Q(K);
        ans = (ans + ex_pow(N, q - 1)) % MOD;
        K ^= (1 << (q - 1));
    }
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}