/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-24 22:35:03
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
set<int> s;
vector<int> v;

void solve () {
    s.clear();
    v.clear();
    int a, b;
    cin >> a >> b;
    int N = a + b;
    int SA = (N + 1) / 2;
    for (int i = 0; i <= min(a, b); i++) {
        int p = SA - min(a, b) + 2 * i;
        s.insert(p);
        s.insert(N - p);
    }
    cout << s.size() << endl;
    for (int s0 : s) {
        v.push_back(s0);
    }
    for (int i = 0; i < s.size(); i++) {
        cout << v[i];
        if (i == s.size() - 1) cout << endl;
        else cout << ' ';
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}