/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-01-29 17:28:41
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int N;
    vector<int> v;
    cin >> N;
    v.clear();
    for (int i = 1; i <= N; i++) {
        int a;
        cin >> a;
        v.push_back(a);
    }
    sort(v.begin(), v.end());
    int mx = v[N-1], ans = 0;
    for (int i = N-1; i>= 0; i--) {
        if (mx == v[i]) continue;
        ans += (mx - v[i]);
        for (int j = 0; j < i; j++) {
            v[j] += (mx - v[i]);
        }
    }
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}