/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-17 19:05:03
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 100 + 9;
int result[MAXN], visit[MAXN];
void output(int i, int n) {
    int f = 0;
    cout << "? ";
    for (int j = 1; j <= n; j++) {
        cout << (f == 0 ? i : n + 1 - i);
        if (j == n) cout << endl;
        else cout << ' ';
        f = 1-f;
    }
    cout.flush();
}
void solve () {
    int n, rs;
    memset(result, 0, sizeof(result));
    memset(visit, 0, sizeof(visit));
    cin >> n;
    for (int i = 1; i < n; i++) {
        output(i, n);
        cin >> rs;
        if (rs != 0) {
            int q = (rs % 2 == 0) ? (n - i + 1) : i;
            result[rs] = q;
            visit[q] = 1;
            continue;
        }
        output(n+1-i, n);
        cin >> rs;
        int q = (rs % 2 == 0) ? i : (n-i+1);
        result[rs] = q;
        visit[q] = 1;
    }
    int lst;
    for (int i = 1; i <= n; i++) {
        if (visit[i] == 0) lst = i;
    }
    cout << "! ";
    for (int i = 1; i <= n; i++) {
        if (result[i] > 0) cout << result[i];
        else cout << lst;
        if (i == n) cout << endl;
        else cout << ' ';
    }
    cout.flush();
}

signed main() {
    fast_stream();
    int t;
//    cin >> t;
    t = 1;
    while (t--) {
        solve();
    }
}