/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-24 22:35:03
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N, MOD;
int dp[MAXN], dp_sum[MAXN];

void solve () {

}

signed main() {
    fast_stream();
    dp[1] = dp_sum[1] = 1;
    cin >> N >> MOD;
    for (int n = 2; n <= N; n++) {
        dp[n] = dp_sum[n-1];
        for (int z = 2; z <= n;) {
            int z0 = n / (n / z);
            if (z0 >= n) z0 = n;
            int delta = ((z0 - z + 1) * dp[n / z]) % MOD;
            dp[n] = (dp[n] + delta) % MOD;
            z = z0 + 1;
        }
        dp_sum[n] = (dp[n] + dp_sum[n-1]) % MOD;
    }
    cout << dp[N] % MOD << endl;
}