/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-28 22:35:02
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
#define plus(x) ((x + 1) % 2)
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7ffffffffffff;
const int MAXN = 1e4 + 9;
struct node {
    int l, r, null;
    int length() {
        return r - l;
    }
} dp[2][];
void solve () {

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}