/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-08 22:35:01
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N;
string s;
char rs[55][55];
int a[55];

void solve () {
    cin >> N >> s;
    int n2 = 0;
    for (int i = 0; i < N; i++) a[i+1] = s[i]-'0', n2 += (s[i] == '2');
    if (n2 == 1 || n2 == 2) cout << "NO" << endl;
    else {
        cout << "YES" << endl;
        for (int i = 1; i <= N; i++) {
            for (int j = 1; j <= N; j++) {
                if (i == j) rs[i][j] = 'X';
                else if (a[i] == 1) {
                    for (int q = 1; q <= N; q++) if (q != i) rs[i][q] = rs[q][i] = '=';
                } else if (a[j] == 1) {
                    for (int q = 1; q <= N; q++) if (q != j) rs[j][q] = rs[q][j] = '=';
                } else {
                    rs[i][j] = rs[j][i] = '=';
                }
            }
        }
        vector<int> v;
        v.clear();
        for (int i = 1; i <= N; i++) if (a[i] == 2) v.push_back(i);
        if (v.size() >= 2) {
            for (int i = 0; i < v.size(); i++) {
                rs[v[i]][v[(i + 1) % v.size()]] = '+';
                rs[v[(i + 1) % v.size()]][v[i]] = '-';
            }
        }
        for (int i = 1; i <= N; i++) {
            for (int j = 1; j <= N; j++) {
                cout << rs[i][j];
            }
            cout << endl;
        }
    }

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}