/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-28 22:35:02
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int arr[MAXN];
deque<int> dq;
void solve () {
    while (!dq.empty()) dq.pop_front();
    int n;
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> arr[i];
    dq.push_back(arr[1]);
    for (int i = 2; i <= n; i++) {
        if (arr[i] <= dq.front()) dq.push_front(arr[i]);
        else dq.push_back(arr[i]);
    }
    for (int i = 1; i <= n; i++) {
        cout << dq.front();
        dq.pop_front();
        if (i == n) cout << endl;
        else cout << ' ';
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}