/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-30 17:34:29
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
void _swap(int &a, int &b, int &c) {
    if (a < b) swap(a, b);
    if (b < c) swap(b, c);
    if (a < b) swap(a, b);
}
void solve () {
    int a, b, c, m; cin >> a >> b >> c >> m; _swap(a, b, c);
    if (a + b + c - 3 < m) { cout << "NO" << endl; return; }
    if (a - b - c - 1 > m) { cout << "NO" << endl; return; }
    cout << "YES" << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}