/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-10 22:35:01
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int arr[1003];
void solve () {
    int N;
    cin >> N;
    int c = 0;
    arr[++c] = 1;
    for (int i = 2; i <= N; i++) {
        int a = 3 * arr[c];
        if (a > 1000000000) { cout << "NO" << endl; return;  }
        arr[++c] = a;
    }
    cout << "YES" << endl;
    for (int i = 1; i < N; i++) cout << arr[i] << ' ';
    cout << arr[N] << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}