/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-24 15:41:41
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int a, b, c;
    cin >> a >> b >> c;
    int ans = abs(a + c - 2 * b) % 3;
    cout << (ans >= 1 ? 1 : 0) << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}