/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-24 18:05:04
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int ex_pow(int a, int b) {
    int ans = 1;
    for (int i = 1; i <= b; i++) ans *= a;
    return ans;
}

void solve () {
    int n, a, n0 = 0, n1 = 0;
    cin >> n;
    for (int i = 1; i <= n; i++) {
        cin >> a;
        if (a == 0) n0++;
        if (a == 1) n1++;
    }
    cout << (n1 * ex_pow(2, n0)) << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}