/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-11 22:35:04
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N, M, mp[103][103];
void solve () {
    cin >> N >> M;
    for (int i = 1; i <= N; i++) {
        string buf;
        cin >> buf;
        for (int j = 0; j < M; j++) mp[i][j+1] = buf[j] - '0';
    }

    for (int i = 2; i <= N; i++) {
        for (int j = 1; j <= M; j++) {
            if (mp[i][j] ^ mp[i-1][j]) {
                if (j >= 2 && mp[i-1][j-1] == 1 && mp[i][j-1] == 1) { cout << "NO" << endl; return; }
                if (j < M && mp[i-1][j+1] == 1 && mp[i][j+1] == 1) {  cout << "NO" << endl; return; }
            }
        }
    }
    cout << "YES" << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}