/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-03 21:38:48
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int A, mx = 0;
    cin >> A;
    while(A > 0) {
        mx = max(mx, A % 10);
        A /= 10;
    }
    cout << mx << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}