/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-13 22:35:01
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int arr[44];
set<int> sr;

void solve () {
    int n;
    cin >> n;
    sr.clear();
    for (int i = 1; i <= n; i++) cin >> arr[i];
    for (int i = 1; i <= n; i++) {
        for (int j = i + 1; j <= n; j++) {
            int q = abs(arr[i] - arr[j]);
            if (q > 0) sr.insert(q);
        }
    }
    if (sr.empty()) cout << -1 << endl;
    else {
        int ans = *sr.begin();
        for (int q : sr) {
            ans = __gcd(ans, q);
        }
        cout << ans << endl;
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}