/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-06 17:55:03
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
int arr[MAXN];
void solve () {
    int N;
    cin >> N;
    bool all_zero = true;
    for (int i = 1; i <= N; i++) cin >> arr[i], all_zero = all_zero && (arr[i] == 0);
    if (all_zero) { cout << 0 << endl; return; }
    sort(arr + 1, arr + 1 + N);
    int maxn = arr[N], last = 0;
    for (int i = 1; i < N; i++) last += arr[i];
    cout << 1 + max(0ll, (maxn - last - 1)) << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}