/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-12 23:42:45
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
int N, ans[MAXN];
deque<int> dq;
void solve () {
    cin >> N;
    int a, b;
    cin >> a >> b;
    if ((a + b + 2) > N || abs(a-b) > 1) cout << -1 << endl;
    else {
        dq.clear();
        for (int i = 1; i <= N; i++) dq.push_back(i);
        bool front = true;
        int c = min(a, b);
        for (int i = 1; i <= c; i++) {
            if (front) ans[i] = dq.front(), dq.pop_front();
            else ans[i] = dq.back(), dq.pop_back();
            front = !front;
        }
        if (a > b) {
            
        }
        else if (a < b) {

        }
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}