/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-20 19:35:02
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
#define lower(x) (x >> 1)
#define upper(x) ((x>>1) + (x&1))
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

map<int, int> mp;
bool dfs(int v) {
    if (mp[v] > 0) {
        mp[v]--;
        return true;
    }
    if (v <= 1) return false;
    return dfs(lower(v)) && dfs(upper(v));
}
void solve () {
    mp.clear();
    int N, sum = 0; cin >> N;
    for (int i = 1; i <= N; i++) {
        int a; cin >> a;
        mp[a]++;
        sum += a;
    }
    if (dfs(sum)) cout << "YES" << endl;
    else cout << "NO" << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) solve();
}