/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-17 19:05:03
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
int visit[MAXN];
void solve () {
    int n, m;
    cin >> n >> m;
    for (int i = 1; i <= n; i++) visit[i] = 0;
    while (m--) {
        int a, b, c;
        cin >> a >> b >> c;
        visit[b] = 1;
    }
    int root;
    for (int i = 1; i <= n; i++) {
        if (visit[i] == 0) {root = i; break;}
    }
    for (int i = 1; i <= n; i++) {
        if (i == root) continue;
        cout << i << ' ' << root << endl;
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}