/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-28 22:35:02
 */
#include <bits/stdc++.h>

using namespace std;
int mp[12][21], v[12][21];

int main() {
    int T;
    cin >> T;
    LOP:;
    while (T--) {
        int n, m, k;
        cin >> n >> m >> k;
        for (int i = 0; i < 12; i++) for (int j = 0; j < 21; j++) mp[i][j] = v[i][j] = 0;
        for (int i = 1; i <= n; i++) {
            string s;
            cin >> s;
            for (int j = 1; j <= m; j++) {
                v[i][j] = mp[i][j] = s[j - 1] == '*';
            }
        }
        for (int i = n; i >= 1; i--) {
            for (int j = 1; j <= m; j++) {
                if (mp[i][j] == 0) continue;
                int d0 = 0;
                for (int d = 0; ; d++) {
                    if (i - d <= 0) break;
                    if (j - d <= 0 || j + d > m) break;
                    if (mp[i-d][j-d] == 0 || mp[i-d][j + d] == 0) break;
                    d0 = d;
                }
                if (d0 < k) continue;
                for (int d = 0; d <= d0; d++) {
                    v[i - d][j + d] = v[i - d][j - d] = 0;
                }
            }
        }

        for (int i = 1; i <= n; i++) {
            for (int j = 1; j <= m; j++) {
                if (v[i][j] == 1) {
                    cout << "NO" << endl;
                    goto LOP;
                }
            }
        }
        cout << "YES" << endl;
    }
}