/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-01-29 17:28:41
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
#define int long long
int N;

void input(int c) {
    cout << "+ " << c << endl;
    fflush(stdout);
}
int output() {
    int x;
    cin >> x;
    return x;
}

signed main() {
    cin >> N;
    int oXmin = 1, oXmax = N-1;
    int nXmin = 1, nXmax = N-1;
    while (oXmin < oXmax) {

    }
}