/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-10 17:05:01
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int a[MAXN], b[MAXN], ca[MAXN], cb[MAXN];

void solve () {
    int N, ans = 0;
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> a[i] >> b[i], ca[a[i]]++, cb[b[i]]++;
    for (int i = 1; i <= N; i++) ans += (ca[a[i]] - 1) * (cb[b[i]] - 1);
    cout << (N * (N - 1) * (N - 2) / 6) - ans << endl;
    for (int i = 1; i <= N; i++) ca[a[i]]--, cb[b[i]]--;
}

signed main() {
    memset(ca, 0, sizeof(ca));
    memset(cb, 0, sizeof(cb));
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}