/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-18 13:46:30
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int f[26];
void solve () {
    string a, b;
    cin >> a >> b;
    for (int i = 0; i < 26; i++) f[a[i] - 'a'] = i;
    int ans = 0;
    for (int j = 1; j < b.size(); j++) {
        ans += abs(f[b[j]-'a'] - f[b[j-1]-'a']);
    }
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}