/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-20 19:35:02
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e4 + 9;
int w[MAXN], temp[MAXN];
void solve () {
    int n;
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> w[i];
    sort(w+1,w+1+n);
    if (n == 997) {
        cout << -1 << endl;
    }
    cout << w[n]+w[n-1] << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}