/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-12 23:42:45
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int visit[MAXN], prime[MAXN], cnt;

void init() {
    cnt = 0;
    memset(visit, 0, sizeof(visit));
    for (int i = 2; i < MAXN; i++) {
        if (visit[i] == 0) prime[++cnt] = i;
        if (cnt > 1000) break;
        for (int j = 1; j <= cnt && i * prime[j] < MAXN; j++) {
            visit[i * prime[j]] = 1;
            if (i % prime[j] == 0) break;
        }
    }
}

void solve () {
    int N;
    cin >> N;
    for (int i = 1; i < N; i++) cout << prime[i] << ' ';
    cout << prime[N] << endl;
}

signed main() {
    init();
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}