/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-26 22:35:02
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 5009;
int dp[MAXN];

void solve () {
    int N;
    string buf;
    cin >> N >> buf;
    dp[1] = N;
    for (int i = 2; i <= N; i++) {
        int Ans = N - i + 1;
        for (int j = 1; j < i; j++) {
            if (buf[j-1] < buf[i-1]) Ans = max(Ans, dp[j] + N - i + 1);
            else if (buf[j-1] > buf[i-1]) continue;
            else {
                int i0 = i, j0 = j;
                while (i0 < N && j0 < N) {
                    if (buf[j0] < buf[i0]) { Ans = max(Ans, dp[j] + N - i0); break;}
                    else if (buf[j0] > buf[i0]) break;
                    i0++, j0++;
                }
            }
        }
        dp[i] = Ans;
    }
    int ans = -1;
    for (int i = 1; i <= N; i++) ans = max(ans, dp[i]);
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}