/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-03 22:13:10
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N, idx[MAXN];
pair<int, int> a[MAXN];

void solve () {
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> a[i].first, a[i].second = i;
    sort(a + 1, a + 1 + N);
    int pos = 0, Ans = 0;
    for (int i = N; i >= 1; i--) {
        pos = -pos + (pos <= 0);
        idx[a[i].second] = pos;
        Ans += (pos < 0 ? -pos : pos) * a[i].first;
    }
    cout << 2 * Ans << endl;
    cout << 0 << ' ';
    for (int i = 1; i <= N; i++) {
        cout << idx[i];
        if (i == N) cout << endl;
        else cout << ' ';
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}