/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-06 17:55:03
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int land[103];

void solve () {
     int N;
     cin >> N;
     for (int i = 1; i <= N; i++) cin >> land[i];
     int st = 1, ed = N;
     for (int i = N - 1; i >= 1; i--) {
         if (land[i]) ed = i;
         else break;
     }
     for (int i = 2; i <= N; i++) {
         if (land[i]) st = i;
         else break;
     }
     if (st + 1 >= ed) cout << 0 << endl;
     else cout << ed - st << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}