/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-04 16:46:12
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int candies[MAXN];
void solve () {
    int N, sum = 0;
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> candies[i], sum += candies[i];
    if (sum % N != 0) {
        cout << -1 << endl;
    } else {
        int arv = sum / N, ans = 0;
        for (int i = 1; i <= N; i++) ans += candies[i] > arv;
        cout << ans << endl;
    }

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}