/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-08 23:05:02
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    int n;
    cin >> n;
    if (n % 2 == 1) cout << n / 2 << ' ' << n / 2 + 1 << endl;
    else cout << -n + 1 << ' ' << n << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}