/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-03 22:13:10
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 109;
int N, L, R, K;
int arr[MAXN];

void solve () {
    int cnt = 0, p, ans = 0;
    cin >> N >> L >> R >> K;
    for (int i = 1; i <= N; i++) {
        cin >> p;
        if (p >= L && p <= R) arr[++cnt] = p;
    }
    sort(arr + 1, arr + 1 + cnt);

    for (int i = 1; i <= cnt; i++) {
        if (arr[i] <= K) K-=arr[i], ans++;
        else break;
    }
    cout << ans << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}