/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-26 22:43:29
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 105;
int A[MAXN], B[MAXN], N;

void solve () {
    cin >> N;
    for (int i = 0; i < N; i++) cin >> A[i];
    for (int j = 0; j < N; j++) cin >> B[j];
    sort(A, A+N);
    sort(B, B+N);
    for (int i = 0; i < N; i++) if (B[i] - A[i] != 0 && B[i] - A[i] != 1) { cout << "NO" << endl; return; }
    cout << "YES" << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}