/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-30 23:39:22
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 888;
int ori[MAXN];
pair<int, int> arr[MAXN / 2];

void solve () {
    int N, n;
    cin >> N;
    n = N / 2;
    for (int i = 1; i <= N; i++) cin >> ori[i];
    for (int i = 1; i <= n; i++) arr[i].first = ori[2 * i -1], arr[i].second = ori[2 * i];
    int tot = 0;

    for (int i = 1; i <= n; i++) {
        tot += min(arr[i].first, arr[i].second);
        if (arr[i].first <= arr[i].second) {
            int rht = arr[i].second - arr[i].first;
            for (int j = i-1; j >= 1; j--) {
                if (rht + arr[j].second < arr[j].first) {
                    tot += (arr[j].second + rht);
                    break;
                }
                if (j == 1) {
                    tot += (rht + arr[j].second == arr[j].first);
                    break;
                }
                tot += arr[j].first;
                rht += (arr[j].second - arr[j].first);
            }
        }
    }
    cout << tot << endl;
}
signed main() {
    fast_stream();
    int t;
//    cin >> t;
    t = 1;
    while (t--) {
        solve();
    }
}