/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-26 22:35:02
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e4 + 9;
int dig[MAXN];

void solve () {
    int N, zero = -1;
    string buf;
    cin >> N >> buf;
    for (int i = 0; i < N; i++) {
        dig[i] = buf[i] - '0';
        if (dig[i] == 0) zero = i + 1;
    }

    if (zero == -1) cout << 1 << ' ' << N - 1 << ' ' << 2 << ' ' << N << endl;
    else if (zero <= N / 2) {
        cout << zero << ' ' << N << ' ' << zero+1 << ' ' << N << endl;
    } else {
        cout << 1 << ' ' << zero << ' ' << 1 << ' ' << zero - 1 << endl;
    }

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}