/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-01-29 17:28:41
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

bool judge(int a, int b, int c) {
    int k = 2 * b - c;
    if (k >= a && k % a == 0) return true;
    k = 2 * b - a;
    if (k >= c && k % c == 0) return true;
    k = a + c;
    if (k % 2 == 0) {
        k /= 2;
        if (k >= b && k % b == 0) return true;
    }
    return false;
}

void solve () {
    int a, b, c;
    cin >> a >> b >> c;
    if (judge(a, b, c)) cout << "YES" << endl;
    else cout << "NO" << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}