/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-03 22:35:05
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e6 + 3;

void solve () {
    // a & b > a ^ b
    /* 8 1 3 3 1 2
     * 1000
     *
     * 0001
     * 0011
     * 0011
     * 0001
     * 0010
     * // all 0 a & b == a ^ b
     * // all 1 奇数个1 a&b == a ^ b 偶数个1 a&b>a^b
     * // else 奇数个1 a&b < a ^ b 偶数个1 a&b == a^b
     */
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}