/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-11-26 22:43:29
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
#define int long long

int input(int l, int r) {
    int result;
    cout << "? " << l << ' ' << r << endl;
    cout.flush();
    cin >> result;
    return result;
}
void solve () {
    int N, A, B, C;
    cin >> N;
    A = input(1, N);
    int L = 1, R = N;
    while (abs(R - L) > 1) {
        int md = (L + R) >> 1;
        int tmp = input(md, N);
        if (tmp < A) R = md;
        else L = md;
    }
    if (R > L) {
        if (input(R, N) == A) L = R;
    }
    B = input(L + 1, N);
    int j = L + 1 + A - B;
    C = A - (j - L) * (j - L - 1) / 2;
    int k = j + (sqrt(8 * C + 1) - 1) / 2;
    cout << "! " << L << ' ' << j << ' ' << k << endl;
    cout.flush();
}

signed main() {
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}