/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-26 22:35:02
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 3e5 + 9;
int arr[MAXN], sum[MAXN];

void solve () {
    int N, Q;
    string buf;
    cin >> N >> Q;
    cin >> buf;
    sum[0] = 0;
    for (int i = 1, mul = 1; i <= N; i++, mul = -mul) {
        arr[i] = mul * (buf[i-1] == '+' ? 1 : -1);
        sum[i] = sum[i-1] + arr[i];
    }
    while(Q--) {
        int l, r, len;
        cin >> l >> r;
        len = r - l + 1;
        if (len % 2 == 0) {
            cout << ((sum[r] - sum[l-1]) == 0 ? 0 : 2) << endl;
        } else {
            cout << 1 << endl;
        }
    }

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}