/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-30 22:35:10
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 109;
int arr[MAXN], n;

void solve () {
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> arr[i];
    int index = 0, tot = 0;
    for (int i = 1; i <= n; i++) {
        index++;
        if (arr[i] > index) { tot += (arr[i] - index); index = arr[i]; }
    }
    cout << tot << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}