/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-13 22:35:01
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 4e5 + 9;
int x[MAXN], n, k;
bool cmp(int a, int b) { return a > b; }
void solve () {
    cin >> n >> k;
    for (int i = 1; i <= k; i++) cin >> x[i];
    sort(x+1, x+1+k, cmp);
    int ans = 0, cat = 0;
    for (int i = 1; i <= k; i++) {
        if (x[i] <= cat) break;
        ans ++;
        cat += (n - x[i]);
    }
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}