/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-24 22:35:03
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1000;
int a[MAXN];

bool judge(int n) {
    for (int i = 1; i <= n; i++) {
        if (a[i] != i) return false;
    }
    return true;
}

void solve () {
    int N;
    cin >> N;
    for (int i = 1; i <= N; i++) cin >> a[i];
    int i = 1;
    while(1) {
        int start = (i % 2 == 1) ? 1 : 2;
        int end = (i % 2 == 1) ? N - 2 : N - 1;
        if (judge(N)) {
            cout << (i-1) << endl;
            return;
        }
        for (int j = start; j <= end; j += 2) {
            if (a[j] > a[j+1]) swap(a[j], a[j+1]);
        }
        i++;
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}