/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-08-24 22:35:03
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
typedef pair<int, int> pr;
pr arr[MAXN];
int sum[MAXN];

void solve() {
    int N, K, S;
    cin >> N;
    for (int i = 1; i <= N; i++) {
        cin >> K;
        int mxn = -1;
        for (int j = 0; j < K; j++) {
            cin >> S;
            mxn = max(mxn, S + 1 - j);
        }
        arr[i] = make_pair(mxn, K);
    }

    sort(arr+1, arr+1+N);
    sum[0] = 0;
    for (int i = 1; i <= N; i++) {
        sum[i] = sum[i-1] + arr[i].second;
    }
    int st = 0, tot = 0;
    for (int i = 1; i <= N; i++) {
        if (tot >= arr[i].first) tot += arr[i].second;
        else {
            tot = arr[i].first + arr[i].second;
            st = arr[i].first - sum[i-1];
        }
    }

    cout << st << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}