/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-20 19:35:02
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

int cnt[26];
void solve () {
    string s;
    cin >> s;
    int L = s.length();
    for (int i = 0; i < 26; i++) cnt[i] = 0;
    for (int i = 0; i < L; i++) cnt[s[i]-'a']++;
    int I = 0;
    for (;I < L;I++) {
        if (cnt[s[I]-'a'] > 1) cnt[s[I]-'a']--;
        else break;
    }
    string ans = s.substr(I);
    cout << ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}