/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-03 22:35:05
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
pair<int, int> arr[MAXN];
int n, x;
bool can_swap(int i, int j) {
    if (i > j) swap(i, j);
    if (j - i >= x) return true;
    if (i - 1 >= x) return true;
    if (n - j >= x) return true;
    return false;
}
void solve () {
    cin >> n >> x;
    for (int i = 1; i <= n; i++) cin >> arr[i].first, arr[i].second = i;
    sort(arr + 1, arr + 1 + n);
    for (int i = n; i >= 1; i--) {
        if (i == arr[i].second) continue;
        if (!can_swap(i, arr[i].second)) {cout << "NO" << endl; return;}
    }
    cout << "YES" << endl;

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}