/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-05 18:20:15
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    string s;
    cin >> s;
    int L = s.length();
    if ((s[L-1] - '0') % 2 == 0) cout << 0 << endl;
    else if ((s[0] - '0') % 2 == 0) cout << 1 << endl;
    else {
        bool ok = false;
        for (int i = 1; i < L - 1; i++) {
            if ((s[i] - '0') % 2 == 0) {
                ok = true;
                break;
            }
        }
        cout << (ok ? 2 : -1) << endl;
    }

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}