/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-27 15:50:59
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 105;
int N;

void solve () {
    cin >> N;
    int Sum = 0;
    for (int i = 1; i <= N; i++) {
        int h;
        cin >> h;
        Sum += h;
    }
    cout << (Sum % N == 0 ? 0 : 1) << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}