/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-12-22 17:04:07
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 1e5 + 9;
const int Q = 300;
int N, q, p[MAXN], r[MAXN], a[MAXN];

void update(int x, int y) {
    swap(p[x], p[y]);
    swap(r[p[x]], r[p[y]]);

    int ans_x = x, ans_y = y;
    for (int t = 1; t <= Q; t++) ans_x = p[ans_x], ans_y = p[ans_y];
    a[x] = ans_x, a[y] = ans_y;

    int _x = x, _y = y;
    for (int t = 1; t < Q; t++) {
        a[r[_x]] = r[a[_x]];
        a[r[_y]] = r[a[_y]];
        _x = r[_x];
        _y = r[_y];
    }
}

int query(int id, int k) {
    int ans = id;
    while (k >= Q) ans = a[ans], k-=Q;
    while (k > 0) ans = p[ans], k--;
    return ans;
}

signed main() {
    fast_stream();
    cin >> N >> q;
    for (int i = 1; i <= N; i++) cin >> p[i], r[p[i]] = i;
    for (int i = 1; i <= N; i++) {
        int ans = i;
        for (int t = 1; t <= Q; t++) ans = p[ans];
        a[i] = ans;
    }
    while (q--) {
        int t, x, y;
        cin >> t >> x >> y;
        if (t == 1) update(x, y);
        else cout << query(x, y) << endl;
    }
}