/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-12 22:37:06
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

void solve () {
    string s;
    cin >> s;
    int L = s.length(), i, j;
    for (i = 0; i < L; i++) if (s[i] == '0') break;
    for (j = L - 1; j >= 0; j--) if (s[j] == '0') break;
    if (i == L || j == -1) cout << 0 << endl;
    else {
        bool has1 = false;
        for (int k = i; k <= j; k++) {
            if (s[k] == '1') {
                has1 = true;
                break;
            }
        }
        cout << (has1 ? 2 : 1) << endl;
    }

}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}