/* Generated by powerful Codeforces Tool
 * Author: shaw
 * Time: 2022-03-11 22:35:04
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
string Ans;

void dfs(int now, int release, string S) {
    if (release == 0) {
        if (S.length() > Ans.length()) {
            Ans = S;
        } else if (S.length() == Ans.length()) {
            if (S[0] > Ans[0]) Ans = S;
        }
        return;
    }
    if (now > release) {
        return;
    }
    dfs(3-now, release-now, S+((char)(now+'0')));
}

void solve () {
    int N;
    cin >> N;
    Ans = "";
    dfs(1, N, "");
    dfs(2, N, "");
    cout << Ans << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}