/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2022-01-01 18:22:35
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N;
string S;
void solve () {
    int ans;
    cin >> N >> S;
    if (N == 1 || S[0] <= S[1]) { cout << S[0] << S[0] << endl; return; }
    for (ans = 1; ans < N - 1; ans++) {
        if (S[ans] < S[ans+1]) break;
    }
    for (int j = 0; j <= ans; j++) cout << S[j];
    for (int j = ans; j >= 0; j--) cout << S[j];
    cout << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}