/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-08 22:35:01
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int N;
int sum_a[55], sum_b[55];

void solve () {
    string s;
    cin >> N >> s;
    sum_a[0] = sum_b[0] = 0;
    for (int i = 1; i <= N; i++) {
        sum_a[i] = sum_a[i-1] + (s[i-1] == 'a');
        sum_b[i] = sum_b[i-1] + (s[i-1] == 'b');
    }
    for (int i = 1; i <= N; i++) {
        for (int j = i; j <= N; j++) {
            int sa = sum_a[j] - sum_a[i-1], sb = sum_b[j] - sum_b[i-1];
            if (sa == sb) {
                cout << i << ' ' << j << endl;
                return;
            }
        }
    }
    cout << -1 << ' ' << -1 << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}