/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-10-03 22:35:05
 */
//#pragma GCC optimize("Ofast", "inline", "-ffast-math")
//#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
int arr[MAXN];
void solve () {
    int n, H, a, b;
    cin >> n >> H;
    for (int i = 1; i <= n; i++) cin >> arr[i];
    sort(arr+1,arr+1+n);a=arr[n-1], b=arr[n];
    int sq = H / (a + b);
    H -= (a + b) * sq;
    sq *= 2;
    if (H > 0 && H <= b) sq += 1;
    else if (H > b) sq += 2;
    cout << sq << endl;
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}