/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-28 22:35:02
 */
#pragma GCC optimize("Ofast", "inline", "-ffast-math")
#pragma GCC target("avx,sse2,sse3,sse4,mmx")
#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;
set<pair<int, int>> s;
vector<pair<int, int>> v;
void solve () {
    int n, a;
    cin >> n;
    s.clear();
    v.clear();
    for (int i = 1; i <= n; i++) {
        cin >> a;
        if (a <= 0) continue;
        s.insert({a, i});
    }
    int t = 0;
    while (1) {
        if (s.size() <= 1) break;
        t++;
        auto st = s.begin(), ed = --s.end();
        pair<int, int> mn = *st;
        pair<int, int> Mn = *ed;
        s.erase(st), s.erase(ed);
        mn.first --;
        Mn.first --;
        v.push_back({mn.second, Mn.second});
        if (mn.first > 0) s.insert(mn);
        if (Mn.first > 0) s.insert(Mn);
    }
    cout << t << endl;
    for (int i = 0; i < t; i++) {
        cout << v[i].first << ' ' << v[i].second << endl;
    }
}

signed main() {

    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}