/* Generated by powerful Codeforces Tool
 * Author: RichardShaw
 * Time: 2021-09-04 16:46:12
 */

#include<bits/stdc++.h>
using namespace std;
void fast_stream() {
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    cout.tie(0);
}
#define int long long
const int INF = 0x7fffffffffffffff;
const int MAXN = 2e5 + 9;

pair<int, int> divide_count(int d) {
    if (d == 1) return make_pair(0, 0);
    int ans = 0;
    for (int i = 2; i * i <= d; i++) {
        while(d % i == 0) {
            ans++;
            d /= i;
        }
    }
    if (d > 1) {
        ans ++;
    }
    return make_pair(1, ans);

}

void solve () {
    int a, b, k;
    cin >> a >> b >> k;
    int gcd = __gcd(a, b);
    int a0 = a / gcd, b0 = b / gcd;
    pair<int, int> p1 = divide_count(a0), p2 = divide_count(b0), p3 = divide_count(gcd);
    if (k < p1.first + p2.first) {
        cout << "NO" << endl;
    } else if (k <= p1.second + p2.second) {
        cout << "YES" << endl;
    } else {
        int kmax = k - p1.first - p2.first;
        int kmin = k - p1.second - p2.second;
        if (kmin > 2 * p3.second) {
            cout << "NO" << endl;
        } else {
            if (kmax > kmin) cout << "YES" << endl;
            else cout << (kmax > 1 ? "YES" : "NO") << endl;
        }
    }
}

signed main() {
    fast_stream();
    int t;
    cin >> t;
    while (t--) {
        solve();
    }
}